/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Main */

#ifndef _Included_jni_Main
#define _Included_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Main
 * Method:    discretization
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_Main_discretization
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif

