/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_ice1000_Main */

#ifndef _Included_org_ice1000_Main
#define _Included_org_ice1000_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ice1000_Main
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ice1000_Main_foo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
